version: "3"
services:
  hapi-fhir-server:
    build:
      context: ../
      dockerfile: ./run/Dockerfile
    container_name: hapi-fhir-server
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    networks:
      - challenge-network
  hapi-fhir-postgres:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5032:5432"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    networks:
      - challenge-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-saracacador13@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - challenge-network
    restart: unless-stopped

networks:
  challenge-network:
    name: challenge-network
    driver: bridge

volumes:
  hapi-fhir-postgres:
  pgadmin:
